- op: replace
  path: /spec/rules/0/host
  value: app.staging.rriv.org
- op: replace
  path: /spec/tls/0/hosts/0
  value: app.staging.rriv.org
- op: replace
  path: /spec/tls/0/secretName
  value: rriv-staging-org-tls
