apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: registry.digitalocean.com/rriv/web
    newTag: prod
patches:
  - path: deployment.yaml
  - path: ingress.yaml
    target:
      kind: Ingress
      name: web
