name: Pull request

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml
